### PR TITLE
Introduce InputError

### PR DESCRIPTION
**Pull request by mfherbst**
During the parsing stage in run_adc, adcc now throws an InputError as a specialised "ValueError"

### CODE REVIEW

**Review by maxscheurer — APPROVED** [review]

**Comment by maxscheurer** [comment]
What is wrong with the tests?! The error messages look obnoxious 🔥 🚒

**Comment by mfherbst** [comment]
I'm on it. pybind11 found a memory issue in the way we use their interface in the HF provider, so now "our" way of doing it is no longer allowed for safety.

**Comment by maxscheurer** [comment]
Okay, let me know if I can do anything. Is this because of the new pybind11 2.6?

**Comment by mfherbst** [comment]
Yes indeed. The changes were introduced in 2.6.

**Comment by mfherbst** [comment]
And now we are hitting the 4th of https://docs.h5py.org/en/stable/whatsnew/3.0.html#breaking-changes-deprecations ...

**Comment by mfherbst** [comment]
It's always the same when you just want to change a little thing :smile:

**Comment by maxscheurer** [comment]
Will the changes be backward compatible for pb11 and h5?

**Comment by mfherbst** [comment]
For pybind11 it's a bit tricky. The HDF5 stuff I might manage.

**Comment by maxscheurer** [comment]
Yes, pybind11 is probably not as bad.. but since h5 gives runtime errors...

**Comment by mfherbst** [comment]
What do you mean by runtime errors?

**Comment by maxscheurer** [comment]
Ahh never mind... I thought the pybind11 error was thrown at compile time... but it wasn't.. so yeah it does not matter 😄

**Comment by mfherbst** [comment]
Hooray ... nah that was a piece of cake, wasn't it ;)

**Comment by maxscheurer** [comment]
Utterly frustrating...

**Pull request merged**
