### PR TITLE
Add rudimentary Travis CI file

### PR DESCRIPTION
**Pull request by mfherbst**
This PR will finally add CI using Travis.

### CODE REVIEW

**Comment by maxscheurer** [comment]
Travis is now working fine, also on macOS. 👍 
Really nice to finally have this! 🎆

**Comment by mfherbst** [comment]
Great work, thanks :smile:

I'll merge this now. For the discussed testing on MacOS under `gcc@8` (potentially also using High Sierra) we can have another PR.

**Comment by mfherbst** [comment]
@maxscheurer I cleaned up the history and it seems now you have to approve again, because I pushed another commit.
I think I disabled this for the future, because with mainly 2 developers on this repo, this is very hard to keep up in practice. Let me know if you disagree.

**Comment by maxscheurer** [comment]
> I think I disabled this for the future, because with mainly 2 developers on this repo, this is very hard to keep up in practice. Let me know if you disagree.

Yes, once approved, it should be able to go in.

**Pull request merged**
