### PR TITLE
Amend evaluate function

### PR DESCRIPTION
**Pull request by maxscheurer**
This is needed to achieve compatibility with stuff derived off tensors or amplitude vectors (e.g. a complex response vector)...

Probably some changes will also be made in the CG code if needed (I don't want to have an extra CG solver for complex response functions)

### CODE REVIEW

**Comment by maxscheurer** [comment]
@mfherbst seems to work, also with the response vectors (that's why I can now use the CG from `adcc`). I don't know if there's some pitfall that we don't cover with our tests or if the change is acceptable...

**Comment by mfherbst** [comment]
Actually ...
https://github.com/adc-connect/adcc/blob/75dd60b3bc0a5bba1e4f33168201a90b550de1b3/adcc/functions.py#L145-L152
... I just did the same thing in the other branch.

**Comment by mfherbst** [comment]
Ups sorry ... I did not want to close.

**Comment by mfherbst** [comment]
Ok. I think I'll split #71 and we merge some of it. There is no point in us repeating the work.

**Comment by mfherbst** [comment]
I'll do this in #77 if you don't mind.

**Pull request closed without merging**
